spring.application.name=spring-kaixo-mundua
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true

#mysql
spring.datasource.url=jdbc:mysql://mysql:3306/CasaJusta
spring.datasource.username=root
spring.datasource.password=pasahitza
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#esta funcion del dialecto no hace falta ya que lo elige automaticamente
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



